version: '3.8'

services:
  video-watermark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: open-video-watermark
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-change-this-in-production}
      - HOST=0.0.0.0
      - PORT=8000
      - MAX_CONTENT_LENGTH=524288000  # 500MB
      - UPLOAD_FOLDER=/app/uploads
      - PROCESSED_FOLDER=/app/processed
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - watermark-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: watermark-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - video-watermark
    restart: unless-stopped
    networks:
      - watermark-network
    profiles:
      - production

networks:
  watermark-network:
    driver: bridge

volumes:
  uploads:
  processed:
  logs:
